// WARNING:
// This file was generated by the Microsoft SQL Server String Resource Tool 10.0.0.0
// from information in sr.strings
// DO NOT MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
// <auto-generated />

namespace Microsoft.SqlTools.LanguageService
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR
    {
        protected SR()
        { }

        public static CultureInfo Culture
        {
            get
            {
                return Keys.Culture;
            }
            set
            {
                Keys.Culture = value;
            }
        }


        public static string WorkspaceServicePositionLineOutOfRange
        {
            get
            {
                return Keys.GetString(Keys.WorkspaceServicePositionLineOutOfRange);
            }
        }

        public static string ErrorEmptyStringReplacement
        {
            get
            {
                return Keys.GetString(Keys.ErrorEmptyStringReplacement);
            }
        }

        public static string ConnectionServiceConnStringMissingAttestationProtocolWithSecureEnclaves
        {
            get
            {
                return Keys.GetString(Keys.ConnectionServiceConnStringMissingAttestationProtocolWithSecureEnclaves);
            }
        }

        public static string ConnectionServiceConnStringMissingAttestationUrlWithAttestationProtocol
        {
            get
            {
                return Keys.GetString(Keys.ConnectionServiceConnStringMissingAttestationUrlWithAttestationProtocol);
            }
        }

        public static string ConnectionServiceConnStringInvalidAlwaysEncryptedOptionCombination
        {
            get
            {
                return Keys.GetString(Keys.ConnectionServiceConnStringInvalidAlwaysEncryptedOptionCombination);
            }
        }

        public static string ConnectionServiceConnStringInvalidAttestationProtocolNoneWithUrl
        {
            get
            {
                return Keys.GetString(Keys.ConnectionServiceConnStringInvalidAttestationProtocolNoneWithUrl);
            }
        }

        public static string PeekDefinitionNoResultsError
        {
            get
            {
                return Keys.GetString(Keys.PeekDefinitionNoResultsError);
            }
        }

        public static string PeekDefinitionDatabaseError
        {
            get
            {
                return Keys.GetString(Keys.PeekDefinitionDatabaseError);
            }
        }

        public static string PeekDefinitionTypeNotSupportedError
        {
            get
            {
                return Keys.GetString(Keys.PeekDefinitionTypeNotSupportedError);
            }
        }

        public static string PeekDefinitionNotConnectedError
        {
            get
            {
                return Keys.GetString(Keys.PeekDefinitionNotConnectedError);
            }
        }

        public static string PeekDefinitionTimedoutError
        {
            get
            {
                return Keys.GetString(Keys.PeekDefinitionTimedoutError);
            }
        }

        public static string RenameNotSupportedLiveServer
        {
            get
            {
                return Keys.GetString(Keys.RenameNotSupportedLiveServer);
            }
        }

        public static string RenameNotSupported
        {
            get
            {
                return Keys.GetString(Keys.RenameNotSupported);
            }
        }

        public static string WorkspaceServiceBufferPositionOutOfOrder(int sLine, int sCol, int eLine, int eCol)
        {
            return Keys.GetString(Keys.WorkspaceServiceBufferPositionOutOfOrder, sLine, sCol, eLine, eCol);
        }

        public static string WorkspaceServicePositionColumnOutOfRange(int line)
        {
            return Keys.GetString(Keys.WorkspaceServicePositionColumnOutOfRange, line);
        }

        public static string StarExpansionLabel(string starExpression)
        {
            return Keys.GetString(Keys.StarExpansionLabel, starExpression);
        }

        public static string StarExpansionDescription(string starExpression, string columnCount, string columnPreview)
        {
            return Keys.GetString(Keys.StarExpansionDescription, starExpression, columnCount, columnPreview);
        }

        public static string ConnectionServiceConnStringInvalidAuthType(string authType)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidAuthType, authType);
        }

        public static string ConnectionServiceConnStringInvalidColumnEncryptionSetting(string columnEncryptionSetting)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidColumnEncryptionSetting, columnEncryptionSetting);
        }

        public static string ConnectionServiceConnStringInvalidSecureEnclaves(string secureEnclaves)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidSecureEnclaves, secureEnclaves);
        }

        public static string ConnectionServiceConnStringInvalidEncryptOption(string encrypt)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidEncryptOption, encrypt);
        }

        public static string ConnectionServiceConnStringInvalidEnclaveAttestationProtocol(string enclaveAttestationProtocol)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidEnclaveAttestationProtocol, enclaveAttestationProtocol);
        }

        public static string ConnectionServiceConnStringInvalidIntent(string intent)
        {
            return Keys.GetString(Keys.ConnectionServiceConnStringInvalidIntent, intent);
        }

        public static string PeekDefinitionAzureError(string errorMessage)
        {
            return Keys.GetString(Keys.PeekDefinitionAzureError, errorMessage);
        }

        public static string PeekDefinitionError(string errorMessage)
        {
            return Keys.GetString(Keys.PeekDefinitionError, errorMessage);
        }

        public static string ParameterizationDetails(string variableName, string sqlDbType, int size, int precision, int scale, string sqlValue)
        {
            return Keys.GetString(Keys.ParameterizationDetails, variableName, sqlDbType, size, precision, scale, sqlValue);
        }

        public static string ErrorMessageHeader(int lineNumber)
        {
            return Keys.GetString(Keys.ErrorMessageHeader, lineNumber);
        }

        public static string ErrorMessage(string variableName, string sqlDataType, string literalValue)
        {
            return Keys.GetString(Keys.ErrorMessage, variableName, sqlDataType, literalValue);
        }

        public static string DateTimeErrorMessage(string variableName, string sqlDataType, string literalValue)
        {
            return Keys.GetString(Keys.DateTimeErrorMessage, variableName, sqlDataType, literalValue);
        }

        public static string BinaryLiteralPrefixMissingError(string variableName, string sqlDataType, string literalValue)
        {
            return Keys.GetString(Keys.BinaryLiteralPrefixMissingError, variableName, sqlDataType, literalValue);
        }

        public static string ParsingErrorHeader(int lineNumber, int columnNumber)
        {
            return Keys.GetString(Keys.ParsingErrorHeader, lineNumber, columnNumber);
        }

        public static string ScriptTooLarge(int maxChars, int currentChars)
        {
            return Keys.GetString(Keys.ScriptTooLarge, maxChars, currentChars);
        }

        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class Keys
        {
            static ResourceManager resourceManager = new ResourceManager("Microsoft.SqlTools.LanguageService.Localization.SR", typeof(SR).GetTypeInfo().Assembly);

            static CultureInfo _culture = null;


            public const string WorkspaceServiceBufferPositionOutOfOrder = "WorkspaceServiceBufferPositionOutOfOrder";


            public const string WorkspaceServicePositionLineOutOfRange = "WorkspaceServicePositionLineOutOfRange";


            public const string WorkspaceServicePositionColumnOutOfRange = "WorkspaceServicePositionColumnOutOfRange";


            public const string ErrorEmptyStringReplacement = "ErrorEmptyStringReplacement";


            public const string StarExpansionLabel = "StarExpansionLabel";


            public const string StarExpansionDescription = "StarExpansionDescription";


            public const string ConnectionServiceConnStringInvalidAuthType = "ConnectionServiceConnStringInvalidAuthType";


            public const string ConnectionServiceConnStringInvalidColumnEncryptionSetting = "ConnectionServiceConnStringInvalidColumnEncryptionSetting";


            public const string ConnectionServiceConnStringInvalidSecureEnclaves = "ConnectionServiceConnStringInvalidSecureEnclaves";


            public const string ConnectionServiceConnStringInvalidEncryptOption = "ConnectionServiceConnStringInvalidEncryptOption";


            public const string ConnectionServiceConnStringInvalidEnclaveAttestationProtocol = "ConnectionServiceConnStringInvalidEnclaveAttestationProtocol";


            public const string ConnectionServiceConnStringMissingAttestationProtocolWithSecureEnclaves = "ConnectionServiceConnStringMissingAttestationProtocolWithSecureEnclaves";


            public const string ConnectionServiceConnStringMissingAttestationUrlWithAttestationProtocol = "ConnectionServiceConnStringMissingAttestationUrlWithAttestationProtocol";


            public const string ConnectionServiceConnStringInvalidAlwaysEncryptedOptionCombination = "ConnectionServiceConnStringInvalidAlwaysEncryptedOptionCombination";


            public const string ConnectionServiceConnStringInvalidAttestationProtocolNoneWithUrl = "ConnectionServiceConnStringInvalidAttestationProtocolNoneWithUrl";


            public const string ConnectionServiceConnStringInvalidIntent = "ConnectionServiceConnStringInvalidIntent";


            public const string PeekDefinitionAzureError = "PeekDefinitionAzureError";


            public const string PeekDefinitionError = "PeekDefinitionError";


            public const string PeekDefinitionNoResultsError = "PeekDefinitionNoResultsError";


            public const string PeekDefinitionDatabaseError = "PeekDefinitionDatabaseError";


            public const string PeekDefinitionTypeNotSupportedError = "PeekDefinitionTypeNotSupportedError";


            public const string PeekDefinitionNotConnectedError = "PeekDefinitionNotConnectedError";


            public const string PeekDefinitionTimedoutError = "PeekDefinitionTimedoutError";


            public const string RenameNotSupportedLiveServer = "RenameNotSupportedLiveServer";


            public const string RenameNotSupported = "RenameNotSupported";


            public const string ParameterizationDetails = "ParameterizationDetails";


            public const string ErrorMessageHeader = "ErrorMessageHeader";


            public const string ErrorMessage = "ErrorMessage";


            public const string DateTimeErrorMessage = "DateTimeErrorMessage";


            public const string BinaryLiteralPrefixMissingError = "BinaryLiteralPrefixMissingError";


            public const string ParsingErrorHeader = "ParsingErrorHeader";


            public const string ScriptTooLarge = "ScriptTooLarge";


            private Keys()
            { }

            public static CultureInfo Culture
            {
                get
                {
                    return _culture;
                }
                set
                {
                    _culture = value;
                }
            }

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, _culture);
            }


            public static string GetString(string key, object arg0)
            {
                return string.Format(global::System.Globalization.CultureInfo.CurrentCulture, resourceManager.GetString(key, _culture), arg0);
            }


            public static string GetString(string key, object arg0, object arg1)
            {
                return string.Format(global::System.Globalization.CultureInfo.CurrentCulture, resourceManager.GetString(key, _culture), arg0, arg1);
            }


            public static string GetString(string key, object arg0, object arg1, object arg2)
            {
                return string.Format(global::System.Globalization.CultureInfo.CurrentCulture, resourceManager.GetString(key, _culture), arg0, arg1, arg2);
            }


            public static string GetString(string key, object arg0, object arg1, object arg2, object arg3)
            {
                return string.Format(global::System.Globalization.CultureInfo.CurrentCulture, resourceManager.GetString(key, _culture), arg0, arg1, arg2, arg3);
            }


            public static string GetString(string key, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
            {
                return string.Format(global::System.Globalization.CultureInfo.CurrentCulture, resourceManager.GetString(key, _culture), arg0, arg1, arg2, arg3, arg4, arg5);
            }

        }
    }
}
