sudo: required
dist: trusty

os:
  - linux
  - osx

mono: none
dotnet: 2.0.0

# safelist
branches:
  only:
    - master
    - dev

language: csharp
solution: sqltoolsservice.sln

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    else
      export HOMEBREW_NO_AUTO_UPDATE=1
    fi
install:
  - dotnet restore

script:
  - dotnet build src/Microsoft.SqlTools.ServiceLayer
  - dotnet test test/Microsoft.SqlTools.ServiceLayer.UnitTests
