sudo: required
dist: trusty

os:
  - linux
  - osx

mono: none
dotnet: 2.0.0

# safelist
branches:
  only:
    - master
    - dev

language: csharp
solution: sqltoolsservice.sln

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
      sudo apt-get update;
      sudo apt-get install dotnet-sdk-2.0.0;
    else
      brew update;
      brew cask install dotnet;
      export PATH="/usr/local/share/dotnet/:$PATH";
    fi
install:
  - dotnet restore

env:
# Since we are building from root, current directory is the project path
  - ProjectPath=$TRAVIS_BUILD_DIR
  
script:
  - dotnet build src/Microsoft.SqlTools.ServiceLayer
  - dotnet test test/Microsoft.SqlTools.ServiceLayer.UnitTests
