install:
  - set PATH=C:\Ruby22\bin;%PATH%

environment:
    COVERALLS_REPO_TOKEN:  
       secure: ZKnsSln/fw8yOFnJm6VdBmcmnmyOUKP+z/QnV5ponCfX69NR0+sLTeNTJWfGW2VJ

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build src/Microsoft.SqlTools.ServiceLayer

test_script:
  - dotnet test test/Microsoft.SqlTools.ServiceLayer.Test

after_test:
  - cd test/CodeCoverage
  - runintegration.bat
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

cache:
- '%USERPROFILE%\.nuget\packages'