install:
  - set PATH=C:\Ruby22\bin;%PATH%

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build src/Microsoft.SqlTools.ServiceLayer

test_script:
  - dotnet test test/Microsoft.SqlTools.ServiceLayer.Test

after_test:
  - cd test/CodeCoverage
  - npm install -g gulp-cli
  - npm install
  - gulp
  - node_modules/.bin/coveralls < outputCobertura.xml

cache:
- '%USERPROFILE%\.nuget\packages'