# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore src/Microsoft.SqlTools.SqlCore'
  inputs:
    command: restore
    projects: src/Microsoft.SqlTools.SqlCore

- task: DotNetCoreCLI@2
  displayName: 'dotnet build src/Microsoft.SqlTools.SqlCore'
  inputs:
    command: build
    projects: src/Microsoft.SqlTools.SqlCore

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack src/Microsoft.SqlTools.SqlCore'
  inputs:
    command: pack
    packagesToPack: 'src/Microsoft.SqlTools.SqlCore/Microsoft.SqlTools.SqlCore.csproj'
    versioningScheme: 'byBuildNumber'
    arguments: -IncludeReferencedProjects

- task: DotNetCoreCLI@2
  displayName: 'dotnet push src/Microsoft.SqlTools.SqlCore'
  inputs:
   command: 'push'
   packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
   nuGetFeedType : internal
   publishVstsFeed: 'mssqltools'