stages:
- stage: Release
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - task: ExtractFiles@1
      displayName: 'Extract files '
      inputs:
        archiveFilePatterns: '$(System.DefaultWorkingDirectory)/SQL Tools Service/source/source.tar.gz'
        destinationFolder: '$(System.DefaultWorkingDirectory)/sqltoolsservice'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/package'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/SQL Tools Service/drop'
        TargetFolder: '$(System.DefaultWorkingDirectory)/sqltoolsservice/artifacts/package'
    - task: AzureKeyVault@1
      displayName: 'Azure Key Vault: ado-secrets'
      inputs:
        azureSubscription: 'ClientToolsInfra_670062 (88d5392f-a34f-4769-b405-f597fc533613)'
        KeyVaultName: 'ado-secrets'
        SecretsFilter: 'github-distro-mixin-password'
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './$(System.DefaultWorkingDirectory)/AutomatedReleases/AutomatedReleases/sqltoolsserviceRelease.ps1'
        arguments: '-workspace $(System.DefaultWorkingDirectory)/sqltoolsservice -minTag v2.0.0.0 -target master -tagFormat release'
        workingDirectory: '$(System.DefaultWorkingDirectory)/sqltoolsservice'
      env:
        GITHUB_DISTRO_MIXIN_PASSWORD: $(github-distro-mixin-password)
