//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml.Linq;
using Microsoft.SqlTools.Sts2.Contracts;
using Microsoft.SqlTools.Sts2.Runtime.Envelopes;

namespace Microsoft.SqlTools.Sts2.Testing
{
    /// <summary>
    /// Deterministic generators for the STS2 review surface (SPEC §12.3). verify.sh
    /// regenerates these and fails on diff; the committed files are the artifacts
    /// humans review. LF newlines always, regardless of platform.
    /// </summary>
    public static class GeneratedDocs
    {
        private const string Header = "<!-- GENERATED by Microsoft.SqlTools.Sts2.Testing.GeneratedDocs; do not edit by hand. Regenerate: ./scripts/update-sts2-docs.ps1 -->\n";

        /// <summary>File name to generator content, for every doc.</summary>
        public static IReadOnlyDictionary<string, string> All(string repoRoot) => new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["CONTRACT.md"] = Contract(),
            ["TRACE-SCHEMA.md"] = TraceSchema(),
            ["INVARIANTS.md"] = Invariants(),
            ["SCENARIO-MATRIX.md"] = ScenarioMatrix(ScenarioCatalog.Load(Path.Combine(repoRoot, "test", "sts2", "scenarios"))),
            ["STATE-MACHINE.md"] = StateMachine(),
            ["COMPONENTS.md"] = Components(Path.Combine(repoRoot, "src", "sts2")),
        };

        /// <summary>CONTRACT.md: methods, error codes, wire constants.</summary>
        public static string Contract()
        {
            var sb = new StringBuilder(Header);
            sb.Append("# STS2 Wire Contract\n\n");
            sb.Append("Spec version: `").Append(Sts2WireConstants.SpecVersion).Append("`. Method prefix: `")
              .Append(Sts2WireConstants.MethodPrefix).Append("`.\n\n");

            sb.Append("## Methods\n\n| Method | Kind | Milestone | Summary |\n|---|---|---|---|\n");
            foreach (Sts2MethodInfo method in Sts2Methods.All)
            {
                sb.Append("| `").Append(method.Name).Append(method.Toy ? "` (toy)" : "`")
                  .Append(" | ").Append(method.Kind)
                  .Append(" | ").Append(method.Milestone)
                  .Append(" | ").Append(method.Summary).Append(" |\n");
            }

            sb.Append("\n## Stable error codes (`error.data.code`)\n\n| Code | Constant |\n|---|---|\n");
            foreach (FieldInfo field in typeof(Sts2ErrorCodes)
                         .GetFields(BindingFlags.Public | BindingFlags.Static)
                         .Where(f => f.IsLiteral)
                         .OrderBy(f => f.Name, StringComparer.Ordinal))
            {
                sb.Append("| `").Append((string)field.GetRawConstantValue()!).Append("` | Sts2ErrorCodes.").Append(field.Name).Append(" |\n");
            }
            sb.Append("\nJSON-RPC `error.code` is always numeric (I12); these strings are the stable identity.\n");
            return sb.ToString();
        }

        /// <summary>TRACE-SCHEMA.md: envelope schema, kinds, redaction markers.</summary>
        public static string TraceSchema()
        {
            var sb = new StringBuilder(Header);
            sb.Append("# STS2 Trace Schema\n\n");
            sb.Append("Envelope schema id: `").Append(EnvelopeJsonCodec.SchemaId).Append("` (SPEC §8.1). Journal lines are single-line JSON with this field order:\n\n");
            sb.Append("| Field | Type | Meaning |\n|---|---|---|\n");
            sb.Append("| schema | string | envelope schema identifier |\n");
            sb.Append("| runId | string | stable per process run |\n");
            sb.Append("| seq | number | gapless monotonic, assigned by the coordinator (I5) |\n");
            sb.Append("| ts | string | UTC round-trip (Z); replay uses recorded values |\n");
            sb.Append("| kind | string | one of the kinds below |\n");
            sb.Append("| sessionId | string? | logical connection/session id |\n");
            sb.Append("| corr | string? | JSON-RPC id, effect id, or correlation id |\n");
            sb.Append("| cause | number? | seq of the producing envelope; null only for external inbound and root control |\n");
            sb.Append("| type | string | method, command, event, effect, metric, or diagnostic name |\n");
            sb.Append("| configVersion | number | config snapshot version |\n");
            sb.Append("| digest | string | sha256 of the canonical payload, present even when elided |\n");
            sb.Append("| payload | any? | inline payload when capture permits |\n");
            sb.Append("| payloadMeta | any? | redaction/elision metadata |\n");

            sb.Append("\n## Kinds\n\n");
            sb.Append("Whether each kind is emitted in v2.0, and by what. \"Reserved\" kinds are part of the closed schema (SPEC §8.1) but are not produced in v2.0; they are listed so the schema is honest about what a trace can actually contain.\n\n");
            sb.Append("| Kind | Status | Emitted by |\n|---|---|---|\n");
            foreach (string kind in EnvelopeKinds.All.OrderBy(k => k, StringComparer.Ordinal))
            {
                (string status, string by) = KindEmission(kind);
                sb.Append("| `").Append(kind).Append("` | ").Append(status).Append(" | ").Append(by).Append(" |\n");
            }

            sb.Append("\n## Redaction markers\n\n");
            sb.Append("Redacted scalar: `{\"$redacted\":true,\"kind\":\"sql\",\"digest\":\"sha256:...\",\"bytes\":N}` — the wrapper carries the original scalar's authoritative digest (SPEC §8.2).\n");
            sb.Append("Secret token: `secret:ref:<32-hex>:<counter>` — an OPAQUE random reference (derived from no part of the secret); real material lives only in the in-memory side table (SPEC §8.5).\n");
            sb.Append("Canonical payload form: UTF-8, ordinal-sorted keys, no insignificant whitespace, number tokens verbatim (D-0007).\n");
            return sb.ToString();
        }

        /// <summary>Emission status of one envelope kind in v2.0 (SPEC §8.1, §18.10 honesty).</summary>
        private static (string Status, string By) KindEmission(string kind) => kind switch
        {
            EnvelopeKinds.RpcInRequest => ("emitted", "inbound JSON-RPC requests (coordinator)"),
            EnvelopeKinds.RpcInNotify => ("emitted", "inbound JSON-RPC notifications (coordinator)"),
            EnvelopeKinds.RpcOutResult => ("emitted", "Core results (rpc.out.result)"),
            EnvelopeKinds.RpcOutError => ("emitted", "Core errors (rpc.out.error)"),
            EnvelopeKinds.RpcOutNotify => ("emitted", "Core notifications (query.rows, query.complete, ...)"),
            EnvelopeKinds.EffectRequest => ("emitted", "Core effect requests (driver.*, diag.export)"),
            EnvelopeKinds.EffectResponse => ("emitted", "effect-runner observations (driver.queryEvent, ...)"),
            EnvelopeKinds.Control => ("emitted", "session.start, lifecycle.shutdown/exit"),
            EnvelopeKinds.Diagnostic => ("emitted", "Core diagnostics (core.unexpectedInput)"),
            EnvelopeKinds.ConfigChanged => ("emitted", "setCapture (config change, I15)"),
            EnvelopeKinds.Metric => ("emitted (opt-in)", "coordinator metric snapshots when MetricSampleEvery > 0; the live metrics channel always tallies"),
            EnvelopeKinds.Command => ("reserved", "no internal command bus in v2.0"),
            EnvelopeKinds.Event => ("reserved", "query events travel as effect.res (driver.queryEvent), not evt"),
            EnvelopeKinds.TimerDue => ("reserved", "open/close timeouts run inside the effect runner, not as journaled timers"),
            EnvelopeKinds.StateSnapshot => ("reserved", "replay-shortcut snapshot optimization, not produced in v2.0"),
            _ => ("reserved", "-"),
        };

        /// <summary>INVARIANTS.md: I1-I16 with their enforcement points.</summary>
        public static string Invariants()
        {
            (string Id, string Name, string Definition, string ExercisedBy)[] invariants =
            [
                ("I1", "Request terminality", "Every request receives exactly one terminal JSON-RPC result or error.", "scenario runner (M2+)"),
                ("I2", "Query terminality", "Every accepted query emits exactly one query.complete.", "scenario runner (M3)"),
                ("I3", "No output after complete", "No query output follows query.complete for that query.", "scenario runner (M3)"),
                ("I4", "Id validity", "Outbound messages never reference unknown, closed, or disposed ids except stable idempotent responses.", "scenario runner (M2+)"),
                ("I5", "Journal causality", "seq is gapless; every non-root envelope has a valid cause less than its own seq.", "CoordinatorTests.SeqIsGaplessAcrossMixedTraffic, EffectFlowChainsCausesThroughTheJournal"),
                ("I6", "Secret safety", "No raw secret canary, JWT shape, password key, or configured secret appears in any artifact.", "SecretRedactionTests, VerificationCorpusProducer, verify.sh canary scan"),
                ("I7", "Replay determinism", "Replay reproduces the identical outbound digest sequence.", "ReplayTests, sts2-replay verify gate"),
                ("I8", "Lease cleanup", "Driver sessions/readers are disposed by run end; live lease count never exceeds the limit.", "effect runner leases (M2+)"),
                ("I9", "Backpressure", "Unacked row pages per query never exceed windowPages.", "scenario runner (M3)"),
                ("I10", "Stdout frame integrity", "Multiplexer output parses to intact frames with no interleaving.", "MultiplexerSingleWriterTests"),
                ("I11", "Dependency boundary", "STS2 assemblies reference only allowed projects and namespaces.", "DependencyMatrixTests"),
                ("I12", "JSON-RPC error shape", "Response errors have numeric error.code and stable error.data.code.", "CoordinatorTests.UnknownMethodJournalsAndEmitsStableError, MultiplexerContainmentTests"),
                ("I13", "Multiplexer id rewrite", "Server-initiated request ids cannot collide across legacy and STS2; responses restore original ids.", "MultiplexerIdRewriteTests"),
                ("I14", "Lifecycle mirroring", "shutdown and exit flush STS2 without duplicate legacy shutdown responses.", "MultiplexerLifecycleTests, StdioE2ETests"),
                ("I15", "Config traceability", "Every effective config change is journaled and visible in replayed state.", "SetCaptureTests (config.changed + replay-visible configVersion)"),
                ("I16", "State redaction", "diagnostics.state and replay state dumps contain no secrets, row cells, or SQL text unless explicitly permitted.", "ReplayTests.StateDumpIsDeterministicOrderedJson (M3 widens)"),
            ];

            var sb = new StringBuilder(Header);
            sb.Append("# STS2 Invariants\n\nChecked by the scenario runner and simulator on every run (SPEC §14.3). \"(M_n_)\" marks enforcement that arrives with that milestone.\n\n");
            foreach ((string id, string name, string definition, string exercisedBy) in invariants)
            {
                sb.Append("## ").Append(id).Append(" — ").Append(name).Append("\n\n")
                  .Append(definition).Append("\n\n*Exercised by:* ").Append(exercisedBy).Append("\n\n");
            }
            return sb.ToString();
        }

        /// <summary>SCENARIO-MATRIX.md from the scenario catalog.</summary>
        public static string ScenarioMatrix(IReadOnlyList<ScenarioInfo> scenarios)
        {
            ArgumentNullException.ThrowIfNull(scenarios);
            var sb = new StringBuilder(Header);
            sb.Append("# STS2 Scenario Matrix\n\n");
            sb.Append("Total: ").Append(scenarios.Count).Append(" (");
            sb.Append(string.Join(", ", scenarios.GroupBy(s => s.Status).OrderBy(g => g.Key, StringComparer.Ordinal)
                .Select(g => g.Count() + " " + g.Key)));
            sb.Append(").\n\nBy milestone: ");
            sb.Append(string.Join(", ", scenarios.GroupBy(s => s.Milestone).OrderBy(g => g.Key, StringComparer.Ordinal)
                .Select(g => g.Key + "=" + g.Count())));
            sb.Append(". By adapter: ");
            sb.Append(string.Join(", ", scenarios.GroupBy(s => s.Adapter).OrderBy(g => g.Key, StringComparer.Ordinal)
                .Select(g => g.Key + "=" + g.Count())));
            sb.Append(".\n\n| Scenario | Tags | Status | Milestone | Adapter |\n|---|---|---|---|---|\n");
            foreach (ScenarioInfo s in scenarios.OrderBy(s => s.Name, StringComparer.Ordinal))
            {
                sb.Append("| ").Append(s.Name)
                  .Append(" | ").Append(string.Join(", ", s.Tags))
                  .Append(" | ").Append(s.Status)
                  .Append(" | ").Append(s.Milestone)
                  .Append(" | ").Append(s.Adapter).Append(" |\n");
            }
            sb.Append("\nMultiplexer-layer scenarios are realized as unit/E2E tests (SPEC §14.2) and tracked here with adapter=multiplexer so corpus accounting stays honest.\n");
            return sb.ToString();
        }

        /// <summary>STATE-MACHINE.md: Mermaid diagrams for the live machines.</summary>
        public static string StateMachine()
        {
            var sb = new StringBuilder(Header);
            sb.Append("# STS2 State Machines\n\n");
            sb.Append("The connection and query machines are live. The M1 toy machine was removed in M3.\n\n");
            sb.Append("## Connection machine (M2)\n\n");
            sb.Append("One entry per connection in `CoreState.Connections`; `openId` is indexed while an open is in flight.\n\n");
            sb.Append("```mermaid\nstateDiagram-v2\n");
            sb.Append("    [*] --> Opening : v2/connection.open / effect driver.open (openId indexed)\n");
            sb.Append("    Opening --> Open : effect.res ok / result(connectionId, serverInfo); openId released\n");
            sb.Append("    Opening --> [*] : effect.res error / error(Sts2.ConnectionFailed.*)\n");
            sb.Append("    Opening --> [*] : effect.res canceled / error(Sts2.Canceled)\n");
            sb.Append("    Opening --> Opening : v2/connection.cancel / result {} + effect driver.cancelOpen (CancelRequested)\n");
            sb.Append("    Opening --> Opening : v2/connection.close / result {} + effect driver.cancelOpen\n");
            sb.Append("    Open --> Closing : v2/connection.close / effect driver.close\n");
            sb.Append("    Closing --> [*] : effect.res / result {}\n");
            sb.Append("    Closing --> Closing : v2/connection.close / result {} (idempotent)\n");
            sb.Append("```\n\n");
            sb.Append("Unknown ids on cancel/close return `{}` (idempotent, SPEC §7.9). A duplicate in-flight `openId` fails with `Sts2.InvalidRequest`; the `maxConnections` limit fails with `Sts2.Busy`.\n\n");
            sb.Append("## Query machine (M3)\n\n");
            sb.Append("One entry per query in `CoreState.Queries`; one active query per connection (`Sts2.Busy` otherwise). Backpressure: Core grants page credit via `driver.queryAdvance`; the runner's enumerator pull blocks without credit (SPEC §7.8, I9).\n\n");
            sb.Append("```mermaid\nstateDiagram-v2\n");
            sb.Append("    [*] --> Running : v2/query.execute / result(queryId) + effect driver.queryStart(credit)\n");
            sb.Append("    Running --> Running : queryEvent rows / notify query.rows (pagesSent+1, credit-1)\n");
            sb.Append("    Running --> Running : queryEvent resultSet|message / notify\n");
            sb.Append("    Running --> Running : v2/query.ack / effect driver.queryAdvance(newCredit)\n");
            sb.Append("    Running --> CancelRequested : v2/query.cancel / result {} + effect driver.queryCancel\n");
            sb.Append("    Running --> Completed : queryEvent completed|error / notify query.complete (exactly once, I2)\n");
            sb.Append("    CancelRequested --> Completed : queryEvent canceled|completed|error / notify query.complete\n");
            sb.Append("    Running --> Disposed : v2/query.dispose / result {} + effect driver.queryDispose (output suppressed, I3)\n");
            sb.Append("    Completed --> Disposed : v2/query.dispose / result {}\n");
            sb.Append("    Disposed --> [*]\n");
            sb.Append("```\n\n");
            sb.Append("`connection.close` with an active query cancels the query first; the connection closes when the query reaches a terminal state (SPEC §7.9).\n\n");
            sb.Append("Unknown requests produce `Sts2.InvalidRequest`; malformed envelopes produce `core.unexpectedInput` diagnostics. The reducer never throws (SPEC §9.2).\n");
            return sb.ToString();
        }

        /// <summary>COMPONENTS.md from COMPONENT.md fragments plus actual csproj references.</summary>
        public static string Components(string sts2SourceDir)
        {
            var sb = new StringBuilder(Header);
            sb.Append("# STS2 Components\n\n");
            sb.Append("Roles come from each project's COMPONENT.md; references are read from the csproj files on disk. The allowed matrix is SPEC §4; DependencyMatrixTests enforces it (I11).\n\n");

            foreach (string projectDir in Directory.EnumerateDirectories(sts2SourceDir).Order(StringComparer.Ordinal))
            {
                string projectName = Path.GetFileName(projectDir);
                string csprojPath = Path.Combine(projectDir, projectName + ".csproj");
                if (!File.Exists(csprojPath))
                {
                    continue;
                }

                string role = "(no COMPONENT.md)";
                string componentPath = Path.Combine(projectDir, "COMPONENT.md");
                if (File.Exists(componentPath))
                {
                    role = File.ReadLines(componentPath)
                        .FirstOrDefault(l => l.StartsWith("**Role:**", StringComparison.Ordinal))
                        ?.Replace("**Role:**", string.Empty).Trim() ?? role;
                }

                XDocument csproj = XDocument.Load(csprojPath);
                string[] projectRefs = csproj.Descendants("ProjectReference")
                    .Select(r => Path.GetFileNameWithoutExtension(r.Attribute("Include")!.Value.Replace('\\', '/')))
                    .Order(StringComparer.Ordinal).ToArray();
                string[] packageRefs = csproj.Descendants("PackageReference")
                    .Select(r => (r.Attribute("Include") ?? r.Attribute("Update"))!.Value)
                    .Order(StringComparer.Ordinal).ToArray();

                sb.Append("## ").Append(projectName).Append("\n\n");
                sb.Append(role).Append("\n\n");
                sb.Append("- Project references: ").Append(projectRefs.Length == 0 ? "none" : string.Join(", ", projectRefs)).Append('\n');
                sb.Append("- Package references: ").Append(packageRefs.Length == 0 ? "none (BCL only)" : string.Join(", ", packageRefs)).Append("\n\n");
            }
            return sb.ToString();
        }
    }
}
