### YamlMime:ManagedReference
items:
- uid: Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService`1.ConfigChangeCallback
  commentId: T:Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService`1.ConfigChangeCallback
  id: WorkspaceService`1.ConfigChangeCallback
  parent: Microsoft.SqlTools.ServiceLayer.Workspace
  children: []
  langs:
  - csharp
  - vb
  name: WorkspaceService<TConfig>.ConfigChangeCallback
  nameWithType: WorkspaceService<TConfig>.ConfigChangeCallback
  fullName: Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService<TConfig>.ConfigChangeCallback
  type: Delegate
  source:
    remote:
      path: src/Microsoft.SqlTools.ServiceLayer/Workspace/WorkspaceService.cs
      branch: master
      repo: https://kburtram:67c6623fc506400046096af249535f684d9ea40b@github.com/Microsoft/sqltoolsservice.git
    id: ConfigChangeCallback
    path: ../src/Microsoft.SqlTools.ServiceLayer/Workspace/WorkspaceService.cs
    startLine: 72
  assemblies:
  - Microsoft.SqlTools.ServiceLayer
  namespace: Microsoft.SqlTools.ServiceLayer.Workspace
  summary: "\nDelegate for callbacks that occur when the configuration for the workspace changes\n"
  example: []
  syntax:
    content: public delegate Task ConfigChangeCallback(TConfig newSettings, TConfig oldSettings, EventContext eventContext);
    content.vb: Public Delegate Function ConfigChangeCallback(newSettings As TConfig, oldSettings As TConfig, eventContext As EventContext) As Task
    parameters:
    - id: newSettings
      type: '{TConfig}'
      description: The settings that were just set
    - id: oldSettings
      type: '{TConfig}'
      description: The settings before they were changed
    - id: eventContext
      type: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.EventContext
      description: Context of the event that triggered the callback
    return:
      type: System.Threading.Tasks.Task
      description: ''
  nameWithType.vb: WorkspaceService(Of TConfig).ConfigChangeCallback
  modifiers.csharp:
  - public
  - delegate
  modifiers.vb:
  - Public
  - Delegate
  fullName.vb: Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService(Of TConfig).ConfigChangeCallback
  name.vb: WorkspaceService(Of TConfig).ConfigChangeCallback
references:
- uid: Microsoft.SqlTools.ServiceLayer.Workspace
  commentId: N:Microsoft.SqlTools.ServiceLayer.Workspace
  isExternal: false
  name: Microsoft.SqlTools.ServiceLayer.Workspace
  nameWithType: Microsoft.SqlTools.ServiceLayer.Workspace
  fullName: Microsoft.SqlTools.ServiceLayer.Workspace
- uid: '{TConfig}'
  commentId: '!:TConfig'
  definition: TConfig
  name: TConfig
  nameWithType: TConfig
  fullName: TConfig
- uid: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.EventContext
  commentId: T:Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.EventContext
  parent: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
  isExternal: false
  name: EventContext
  nameWithType: EventContext
  fullName: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.EventContext
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: TConfig
  isExternal: false
  name: TConfig
  nameWithType: TConfig
  fullName: TConfig
- uid: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
  commentId: N:Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
  isExternal: false
  name: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
  nameWithType: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
  fullName: Microsoft.SqlTools.ServiceLayer.Hosting.Protocol
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
