//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.SqlServer.Dac;
using Microsoft.SqlTools.Hosting.Protocol;
using Microsoft.SqlTools.ServiceLayer.SqlPackage;
using Microsoft.SqlTools.ServiceLayer.SqlPackage.Contracts;
using Microsoft.SqlTools.ServiceLayer.Test.Common;
using Moq;
using NUnit.Framework;

namespace Microsoft.SqlTools.ServiceLayer.UnitTests.SqlPackage
{
    /// <summary>
    /// Tests for SqlPackageService
    /// </summary>
    public class SqlPackageServiceTests
    {
        private SqlPackageService service;

        [SetUp]
        public void Setup()
        {
            service = SqlPackageService.Instance;
        }

        [Test]
        public void ServiceInstanceShouldBeSingleton()
        {
            // Arrange & Act
            var instance1 = SqlPackageService.Instance;
            var instance2 = SqlPackageService.Instance;

            // Assert
            Assert.AreSame(instance1, instance2);
        }

        [Test]
        public async Task GeneratePublishCommand_WithMinimalParameters_ShouldReturnValidCommand()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            Assert.IsNotNull(capturedResult.Command);
            // Command is generated by SqlPackageCommandBuilder API from hybrid NuGet package
            StringAssert.Contains("/Action:Publish", capturedResult.Command);
            StringAssert.Contains("/SourceFile:", capturedResult.Command);
            StringAssert.Contains("database.dacpac", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithConnectionString_ShouldUseConnectionString()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetConnectionString = "Server=localhost;Database=TestDB;Integrated Security=true;",
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            // SqlPackageCommandBuilder API generates the command with connection string
            StringAssert.Contains("/TargetConnectionString:", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithoutExecutableName_ShouldNotIncludeSqlPackage()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                IncludeExecutableName = false
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            Assert.IsFalse(capturedResult.Command.StartsWith("sqlpackage"));
            StringAssert.StartsWith("/Action:Publish", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithProfile_ShouldIncludeProfilePath()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                ProfilePath = "C:\\test\\publish.publish.xml",
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            // SqlPackageCommandBuilder API includes profile in command
            StringAssert.Contains("/Profile:", capturedResult.Command);
            StringAssert.Contains("publish.publish.xml", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithVariables_ShouldIncludeVariables()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                Variables = new Dictionary<string, string>
                {
                    { "Environment", "Production" },
                    { "Version", "1.0" }
                },
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            // SqlPackageCommandBuilder API formats variables in the command
            StringAssert.Contains("/v:", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithDeploymentOptions_ShouldIncludeNonDefaultOptions()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var deploymentOptions = new DacFx.Contracts.DeploymentOptions();
            deploymentOptions.BooleanOptionsDictionary["IgnoreWhitespace"] = 
                new DacFx.Contracts.DeploymentOptionProperty<bool>(true, "", "");
            deploymentOptions.BooleanOptionsDictionary["DropObjectsNotInSource"] = 
                new DacFx.Contracts.DeploymentOptionProperty<bool>(false, "", "");

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                DeploymentOptions = deploymentOptions,
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            // SqlPackageCommandBuilder API includes deployment options that differ from defaults
            StringAssert.Contains("/p:", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithTargetFile_ShouldIncludeTargetFile()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetFile = "C:\\test\\target.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            StringAssert.Contains("/TargetFile:\"C:\\test\\target.dacpac\"", capturedResult.Command);
        }

        [Test]
        public async Task GeneratePublishCommand_WithException_ShouldReturnErrorResult()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            // Pass null parameters to trigger exception in SqlPackageCommandBuilder API
            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = null,
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsFalse(capturedResult.Success);
            Assert.IsNotNull(capturedResult.ErrorMessage);
            requestContext.Verify(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()), Times.Once);
        }

        [Test]
        public async Task GeneratePublishCommand_WithExcludeObjectTypes_ShouldIncludeMultipleExclusions()
        {
            // Arrange
            var requestContext = new Mock<RequestContext<GeneratePublishCommandResult>>();
            GeneratePublishCommandResult capturedResult = null;
            requestContext.Setup(x => x.SendResult(It.IsAny<GeneratePublishCommandResult>()))
                .Callback<GeneratePublishCommandResult>(r => capturedResult = r)
                .Returns(Task.CompletedTask);

            var deploymentOptions = new DacFx.Contracts.DeploymentOptions();
            deploymentOptions.ExcludeObjectTypes = new DacFx.Contracts.DeploymentOptionProperty<string[]>(
                new string[] { "Logins", "Users", "ServerRoles" }, "", "");

            var parameters = new GeneratePublishCommandParams
            {
                SourceFile = "C:\\test\\database.dacpac",
                TargetServerName = "localhost",
                TargetDatabaseName = "TestDB",
                DeploymentOptions = deploymentOptions,
                IncludeExecutableName = true
            };

            // Act
            await service.HandleGeneratePublishCommandRequest(parameters, requestContext.Object);

            // Assert
            Assert.IsNotNull(capturedResult);
            Assert.IsTrue(capturedResult.Success);
            // SqlPackageCommandBuilder API handles ExcludeObjectTypes formatting
            StringAssert.Contains("/p:", capturedResult.Command);
        }
    }
}
