# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: 0 5 * * *
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchTags: true
    persistCredentials: True
  - task: cesve.one-loc-build.one-loc-build.OneLocBuild@2
    displayName: 'Localization Build: src/LocProject.json'
    inputs:
      locProj: src/LocProject.json
      packageSourceAuth: patAuth
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
